language: java
sudo: false
env:
  matrix:
  - IDEA_VERSION=IC-14.0.4
  - IDEA_VERSION=IC-14.1.6
  - IDEA_VERSION=IC-15.0.2
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  global:
  - secure: GJxFEsmA6nJDtD45okB20WgXlfCY/Zaw90aOXxBAWb3w/7eeIFrolXev4ve+gxDettCArqcsPo53vpyimjFzRI8IZB+MZRnpPEVx3Ux/5eEBf2jMqsoaxmWk5rnKp3DTXjMlaAPSnUJRhrPboxdireQG2mIMa34QGv8tCcM2aLk=
notifications:
  email: false
branches:
  only:
  - master
  - develop
before_script:
- if [ $TRAVIS_BRANCH == 'develop' ]; then export PLUGIN_CHANNEL=nightly; fi
script:
- ./gradlew buildPlugin -PideaVersion=$IDEA_VERSION
after_success:
- curl -Lo travis_after_all.py https://raw.github.com/winterDroid/travis_after_all/master/travis_after_all.py
- python travis_after_all.py
- export $(cat .to_export_back) &> /dev/null
- if [[ $BUILD_LEADER = YES && "$BUILD_AGGREGATE_STATUS" = "others_succeeded" && $TRAVIS_PULL_REQUEST = 'false' ]]; then ./gradlew publishPlugin; fi
after_script:
- echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS
